name: ci
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'
        
      - uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - run: go mod download
        
      - run: npm install --legacy-peer-deps
        working-directory: ./web/app

      - run: go test -cover -coverprofile=coverage.txt -covermode=atomic ./...

      # create a CODECOV_TOKEN secret. see https://github.com/marketplace/actions/codecov
      #- uses: codecov/codecov-action@v1
      #  with:
      #    token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos

      - run: npm run build
        working-directory: ./web/app